name: Build
on: push

jobs:
  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
      with:
        command: bin/rails workarea:test:admin

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
      with:
        command: bin/rails workarea:test:core

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
      with:
        command: bin/rails workarea:test:storefront

  plugins_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      env:
        ACCESS_TOKEN: ${{ secrets.access_token }}
      with:
        command: bin/rails workarea:test:plugins
